name: Main workflow
on: [push]
jobs:
  run:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 14.x
      uses: actions/setup-node@master
      with:
        version: 14.x

    - name: npm install
      run: npm install

    - name: Lint
      run: npm run format-check
  selftest:
    name: Self test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Nox (this workflow ðŸ˜±)
        uses: ./
      - name: Run selftest Noxfile
        run: nox -f selftest.nox.py